services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=Swibee'
      - 'MONGO_INITDB_ROOT_PASSWORD=Welcome1!'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db
    networks:
      - swibee-network

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=Swibee'
      - 'POSTGRES_PASSWORD=Welcome1!'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - swibee-network

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - swibee-network

volumes:
  mongodb-data:
  postgres-data:
  redis-data:

networks:
  swibee-network:
    driver: bridge
