services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - postgres
      - mongodb
      - redis
    environment:
      - 'SPRING_PROFILES_ACTIVE=docker'
    networks:
      - swibee-network
    restart: unless-stopped

  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=Swibee'
      - 'MONGO_INITDB_ROOT_PASSWORD=Welcome1!'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db
    networks:
      - swibee-network
    restart: unless-stopped

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=Swibee'
      - 'POSTGRES_PASSWORD=Welcome1!'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - swibee-network
    restart: unless-stopped

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - swibee-network
    restart: unless-stopped

volumes:
  mongodb-data:
  postgres-data:
  redis-data:

networks:
  swibee-network:
    driver: bridge 