spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:Swibee}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:myuser}
    password: ${DB_PASSWORD:Welcome1!}
    hikari:
      maximum-pool-size: 20
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME:root}:${MONGO_PASSWORD:Welcome1!}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_DATABASE:Swibee}?authSource=admin
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    timeout: 2000ms

server:
  port: 8080
  tomcat:
    max-threads: 200
    min-spare-threads: 10

logging:
  level:
    root: WARN
    dev.swibee: INFO
  file:
    path: /var/log/swibee
    name: swibee.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics 